### ISSUE TITLE
[FEATURE] 엔티티 추가

### ISSUE THREAD

**Issue by Yoon-Jemin** [Hongik-Grad-Project/Back-End#14]
## 📝 Description

> 도메인 작성

## ✔️ Todo
- [x] todo1: 엔티티 추가
- [x] todo2: DB를 H2에서 MySQL로 교체
- [x] todo3: VMS에서 봉사 데이터의 속성을 크롤링

## ETC
기타사항
